apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    tag: latest
  name: python-helloworld
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 6111
      protocol: TCP
      targetPort: 6111
      nodePort: {{ .Values.service.ports.nodePort }}
  selector:
    app: python-helloworld
  type: NodePort
