apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    tag: latest
  name: python-helloworld
  namespace: python-argocd
spec:
  ports:
    - port: 8111
      protocol: TCP
      targetPort: 6111
  selector:
    app: python-helloworld
    tag: latest
  type: ClusterIP
